---
# Install nvidia packages

- name: unwanted packages are removed
  package:
    name: "{{ nvidia_packages_remove }}"
    state: absent
  become: true
  when: nvidia_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ nvidia_packages_repos }}"
    state: "{{ nvidia_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ nvidia_packages_prereq }}"
    state: "{{ nvidia_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ nvidia_packages_install }}"
    state: "{{ nvidia_packages_state }}"
  become: true
